using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;
using BeastCraft.Save;
using NUnit.Framework;

namespace BeastCraft.Tests.EditMode
{
    /// <summary>
    /// Golden save fixtures for every schema version (1-14): each committed input is loaded (and
    /// migrated) by <see cref="SaveSerializer"/> and written back, and the text must equal the
    /// committed expected output byte for byte. The fixtures and outputs were captured on the
    /// Unity-era JsonUtility serializer; the engine-neutral serializer must reproduce them exactly.
    /// <para>
    /// <c>rich-v5</c> is a schema-5 save with every field of every save DTO filled (generated once,
    /// by reflection, then frozen as a file); <c>rich-v1</c>..<c>rich-v4</c> are the same text stamped
    /// with an older SchemaVersion, so every migration runs over every field. <c>rich-v6</c> is the
    /// schema-6 save generated the same way (it adds <c>MapRun.Difficulty</c>), and is the one that
    /// must round-trip unchanged. The <c>min-v*</c> inputs are the small hand-written saves of each
    /// era the migration tests use. Schema 6 (the expedition's difficulty) changed every older
    /// expected output in exactly two places: <c>"SchemaVersion":5</c> became <c>6</c>, and
    /// <c>,"Difficulty":0</c> follows <c>"NodeAttemptsNodeId"</c> in the <c>ActiveRun</c>; no input
    /// of schema 1-5 changed.
    /// </para>
    /// <para>
    /// Schema 7 (the onboarding state, <c>PlayerSave.Tutorial</c>) froze <c>rich-v6</c> as an input and
    /// added <c>rich-v7</c>, the schema-7 save generated the same way, which is now the one that must
    /// round-trip unchanged. Every older expected output changed in exactly these places:
    /// <c>"SchemaVersion":6</c> became <c>7</c>, <c>,"Tutorial":{...}</c> follows <c>"Idle"</c> (a save
    /// that owns a beast counting Hearthglen as cleared), and the beast-less <c>min-v5</c>/<c>min-v6</c>
    /// start Hearthglen (<c>r00</c> unlocked instead of <c>r01</c>). No input changed.
    /// </para>
    /// <para>
    /// Schema 8 (the discovery layer) froze <c>rich-v7</c> as an input and added <c>rich-v8</c>, which is
    /// now the one that must round-trip unchanged. Every older expected output changed in exactly these
    /// places: <c>"SchemaVersion":7</c> became <c>8</c>; every region entry gains
    /// <c>,"DiscoverySeed":…,"Fog":[…],"FoundPoiIds":[],"Completed":false</c> after <c>"BossCleared"</c>
    /// (a campaign region's seed derived from its id, or from the expedition in progress's map seed for
    /// its region; every stage cleared before fog existed revealed whole, the expedition in progress's
    /// trailhead and cleared locations revealed; Hearthglen none); and <c>,"Discovery":{…}</c> (nothing
    /// claimed, pending, unlocked or found) follows <c>"Tutorial"</c>. No input changed.
    /// </para>
    /// <para>
    /// Schema 9 (the compendium's achievements, titles and look tokens) froze <c>rich-v8</c> as an
    /// input and added <c>rich-v9</c>, which is now the one that must round-trip unchanged. Every
    /// older expected output changed in exactly these places: <c>"SchemaVersion":8</c> became <c>9</c>;
    /// <c>,"KinshipJoins":[…]</c> follows <c>"LoreIds"</c> inside <c>"Discovery"</c>; and
    /// <c>,"Achievements":{…},"LookTokens":…</c> (nothing earned, owned, equipped or held) follows
    /// <c>"Discovery"</c>. No input changed.
    /// </para>
    /// <para>
    /// Schema 10 (the Grove, the Wildgarden and the Board) froze <c>rich-v9</c> as an input and added
    /// <c>rich-v10</c>, which is now the one that must round-trip unchanged. Every older expected
    /// output changed in exactly these places: <c>"SchemaVersion":9</c> became <c>10</c>; and
    /// <c>,"Grove":{…},"Garden":{…},"Expeditions":{…}</c> (no habitat, decor, beast affinity, Grove
    /// item, plot, herbarium entry, expedition or story) follows <c>"LookTokens"</c>. No input changed.
    /// </para>
    /// <para>
    /// The NPC dialogue layer (<c>PlayerSave.Npc</c>, the Grove design's D2) was added to this same
    /// schema-10 shape in place, since schema 10 had not shipped on any other branch yet (see
    /// <c>Save.SaveMigrations.AddGrove</c>'s own remarks): <c>rich-v10.input.json</c> was regenerated by
    /// reflection (<c>BEASTCRAFT_UPDATE_GOLDENS=1</c>) to include it, and every expected output (v1-v10,
    /// rich and min) changed in exactly one additional place: <c>,"Npc":{"Dialogue":{"LinesSeen":[…]},
    /// "RequestsFulfilled":[…],"LoreIds":[…],"SideStories":[…]}</c> follows <c>"Expeditions"</c>'s
    /// closing brace (nothing seen, fulfilled, found or reached for the min saves). No other input or
    /// migration changed.
    /// </para>
    /// <para>
    /// Peaceful clears (<c>Campaign.CampaignProgress.LocationsSoothed</c>, the Grove design's D3) was
    /// also added to this same schema-10 shape in place, for the same "schema 10 had not shipped yet"
    /// reason: <c>rich-v10.input.json</c> was regenerated again (<c>BEASTCRAFT_UPDATE_GOLDENS=1</c>),
    /// and every expected output changed in exactly one additional place: <c>,"LocationsSoothed":0</c>
    /// follows <c>ActiveRun</c>'s closing brace, inside <c>"Campaign"</c> (0 for the min saves).
    /// Colour evolutions (D3's other half) added no save field at all: a colour form's ownership and a
    /// beast's applied form reuse the existing <c>PlayerSave.Cosmetics</c>/<c>OwnedBeast.Appearance</c>
    /// shape (<c>Economy.CosmeticRules</c>), so no golden changed for it.
    /// </para>
    /// <para>
    /// Schema 11 (the mid-battle crash refund, <c>PlayerSave.PendingBattleConsumables</c>) froze
    /// <c>rich-v10</c> as an input and added <c>rich-v11</c>, which is now the one that must round-trip
    /// unchanged. Every older expected output changed in exactly these places: <c>"SchemaVersion":10</c>
    /// became <c>11</c>, and <c>,"PendingBattleConsumables":[]</c> follows <c>"Npc"</c>'s closing brace
    /// (nothing pending: an older save never recorded a battle in progress). No input changed.
    /// </para>
    /// <para>
    /// Schema 12 (the "new" markers' seen list, <c>PlayerSave.Seen</c>) froze <c>rich-v11</c> as an input and
    /// added <c>rich-v12</c>, which is now the one that must round-trip unchanged. Every older expected output
    /// changed in exactly these places: <c>"SchemaVersion":11</c> became <c>12</c>, and
    /// <c>,"Seen":{"Gear":[...],"Looks":[...]}</c> follows <c>"PendingBattleConsumables"</c>, listing the gear instance
    /// ids and unlocked look keys that save already owned (the migration marks them seen). <c>,"PreferredDifficulty":N</c>
    /// follows <c>"LocationsSoothed"</c> (the post-game difficulty preference, folded into schema 12 before it shipped:
    /// 1 where the save's expedition was on Hard, <c>rich-v6</c> to <c>rich-v11</c>, else 0). And the placed decor's
    /// <c>X</c>/<c>Y</c> (now fractions of the habitat canvas, clamped to 0-1 on load) read 1 in <c>rich-v10</c> and
    /// <c>rich-v11</c>, whose reflection-filled 64-65 were out of range. <c>rich-v12</c>'s capture fills them in range.
    /// No input changed.
    /// </para>
    /// <para>
    /// Schema 13 (the in-battle pause menu's Retreat, <c>MapRun.NodeRetreats</c>/<c>NodeRetreatsNodeId</c> —
    /// see <c>docs/design/progression-and-saves.md</c>, "Schema 13: Retreat") froze <c>rich-v12</c> as an
    /// input and added <c>rich-v13</c>, which is now the one that must round-trip unchanged. Every older
    /// expected output changed in exactly two places: <c>"SchemaVersion":12</c> became <c>13</c>, and
    /// <c>,"NodeRetreats":N,"NodeRetreatsNodeId":N</c> follows <c>"Difficulty"</c> inside every
    /// <c>ActiveRun</c>. No input changed.
    /// </para>
    /// <para>
    /// Schema 14 (the journal UI kit's menu backdrop picker, <c>CampaignProgress.ReachedBackdropIds</c>/
    /// <c>SelectedBackdropId</c>) froze <c>rich-v13</c> as an input and added <c>rich-v14</c>, which is now
    /// the one that must round-trip unchanged. Every older expected output changed in exactly these
    /// places: <c>"SchemaVersion":13</c> became <c>14</c>, and <c>,"ReachedBackdropIds":[...],
    /// "SelectedBackdropId":"r00"</c> follows <c>"PreferredDifficulty"</c> inside <c>"Campaign"</c>:
    /// Hearthglen (<c>r00</c>) reached by default plus every region already listed in
    /// <c>Campaign.Regions</c> (<see cref="Save.SaveMigrations.AddBackdrops"/> treats an already-unlocked
    /// region as already reached), Hearthglen selected. No input changed.
    /// </para>
    /// </summary>
    public class GoldenSaveTests
    {
        private static readonly string[] MinimalInputs =
        {
            "{\"SchemaVersion\":1,\"Beasts\":[{\"BeastId\":\"b1\",\"Progress\":{\"SpeciesId\":\"emberfox\",\"Level\":4}}]}",
            "{\"SchemaVersion\":2," +
            "\"Beasts\":[{\"BeastId\":\"b1\",\"Progress\":{\"SpeciesId\":\"emberfox\",\"Level\":40,\"Xp\":120}," +
            "\"Skills\":{\"Known\":[],\"Equipped\":[\"\",\"\",\"\"]},\"EquippedGear\":[\"\",\"\",\"\"]}]," +
            "\"Avatar\":{\"Level\":38,\"Xp\":40}," +
            "\"Materials\":{\"Materials\":[],\"ClearedCells\":[],\"Pity\":[]}," +
            "\"Gear\":{\"BeastGear\":[],\"AvatarGear\":[],\"NextInstanceNumber\":1},\"AvatarEquippedGear\":[\"\",\"\",\"\"]}",
            "{\"SchemaVersion\":3," +
            "\"Beasts\":[{\"BeastId\":\"b1\",\"Progress\":{\"SpeciesId\":\"griffin\",\"Level\":14,\"Xp\":5,\"BankedXp\":0}," +
            "\"Skills\":{\"Known\":[],\"Equipped\":[\"\",\"\",\"\"]},\"EquippedGear\":[\"\",\"\",\"\"]}]," +
            "\"Avatar\":{\"Level\":9,\"Xp\":3}," +
            "\"Materials\":{\"Materials\":[{\"MaterialId\":\"essence_shard\",\"Quantity\":2}],\"ClearedCells\":[],\"Pity\":[]}," +
            "\"Gear\":{\"BeastGear\":[],\"AvatarGear\":[],\"NextInstanceNumber\":1},\"AvatarEquippedGear\":[\"\",\"\",\"\"]," +
            "\"Campaign\":{\"Seals\":[],\"Regions\":[{\"RegionId\":\"r01\",\"StagesCleared\":2,\"BossCleared\":false}],\"CurrentRegionId\":\"r01\"," +
            "\"ActiveRun\":{\"RegionId\":\"\",\"Stage\":0,\"Seed\":0,\"Nodes\":[],\"CurrentNodeId\":-1,\"Cleared\":[],\"Attempts\":0,\"NodeAttempts\":0}}}",
            "{\"SchemaVersion\":4," +
            "\"Beasts\":[{\"BeastId\":\"b1\",\"Progress\":{\"SpeciesId\":\"griffin\",\"Level\":14,\"Xp\":5,\"BankedXp\":0}," +
            "\"Skills\":{\"Known\":[],\"Equipped\":[\"\",\"\",\"\"]},\"EquippedGear\":[\"\",\"\",\"\"]," +
            "\"Appearance\":{\"OptionEntries\":[],\"ColorEntries\":[{\"CategoryId\":\"fur\",\"Color\":{\"r\":0.1,\"g\":0.25,\"b\":0.7,\"a\":1}}]}}]," +
            "\"Avatar\":{\"Level\":9,\"Xp\":3}," +
            "\"Materials\":{\"Materials\":[{\"MaterialId\":\"essence_shard\",\"Quantity\":2}],\"ClearedCells\":[],\"Pity\":[]}," +
            "\"Gear\":{\"BeastGear\":[],\"AvatarGear\":[],\"NextInstanceNumber\":1},\"AvatarEquippedGear\":[\"\",\"\",\"\"]," +
            "\"Campaign\":{\"Seals\":[],\"Regions\":[{\"RegionId\":\"r01\",\"StagesCleared\":2,\"BossCleared\":false}],\"CurrentRegionId\":\"r01\"," +
            "\"ActiveRun\":{\"RegionId\":\"\",\"Stage\":0,\"Seed\":0,\"Nodes\":[],\"CurrentNodeId\":-1,\"Cleared\":[],\"Attempts\":0,\"NodeAttempts\":0}}," +
            "\"Gold\":77,\"Consumables\":[],\"Shops\":[],\"Cosmetics\":{\"Unlocked\":[]}," +
            "\"AvatarAppearance\":{\"OptionEntries\":[],\"ColorEntries\":[]}}",
            "{\"SchemaVersion\":5}",
            "{\"SchemaVersion\":6}",
            "{\"SchemaVersion\":7}",
            "{\"SchemaVersion\":8}",
            "{\"SchemaVersion\":9}",
            "{\"SchemaVersion\":10}",
            "{\"SchemaVersion\":11}",
            "{\"SchemaVersion\":12}",
            "{\"SchemaVersion\":13}",
            "{\"SchemaVersion\":14}"
        };

        private static SaveSerializer NewSerializer()
        {
            return new SaveSerializer(new JsonSaveSerializer());
        }

        /// <summary>The frozen schema-5 rich save (never rewritten: schema 6 left every older input as it was).</summary>
        private static string RichV5()
        {
            return GoldenFiles.Read("Saves/rich-v5.input.json");
        }

        /// <summary>The frozen schema-6 rich save (captured by reflection before schema 7; never rewritten).</summary>
        private static string RichV6()
        {
            return GoldenFiles.Read("Saves/rich-v6.input.json");
        }

        /// <summary>The frozen schema-7 rich save (captured by reflection before schema 8; never rewritten).</summary>
        private static string RichV7()
        {
            return GoldenFiles.Read("Saves/rich-v7.input.json");
        }

        /// <summary>The frozen schema-8 rich save (captured by reflection before schema 9; never rewritten).</summary>
        private static string RichV8()
        {
            return GoldenFiles.Read("Saves/rich-v8.input.json");
        }

        /// <summary>The frozen schema-9 rich save (captured by reflection before schema 10; never rewritten).</summary>
        private static string RichV9()
        {
            return GoldenFiles.Read("Saves/rich-v9.input.json");
        }

        /// <summary>The frozen schema-10 rich save (captured by reflection before schema 11; never rewritten).</summary>
        private static string RichV10()
        {
            return GoldenFiles.Read("Saves/rich-v10.input.json");
        }

        /// <summary>The frozen schema-11 rich save (captured by reflection before schema 12; never rewritten).</summary>
        private static string RichV11()
        {
            return GoldenFiles.Read("Saves/rich-v11.input.json");
        }

        /// <summary>The frozen schema-12 rich save (captured by reflection before schema 13; never rewritten).</summary>
        private static string RichV12()
        {
            return GoldenFiles.Read("Saves/rich-v12.input.json");
        }

        /// <summary>The frozen schema-13 rich save (captured by reflection before schema 14; never rewritten).</summary>
        private static string RichV13()
        {
            return GoldenFiles.Read("Saves/rich-v13.input.json");
        }

        /// <summary>The frozen schema-14 rich save (captured by reflection in update mode).</summary>
        private static string RichV14()
        {
            if (GoldenFiles.Updating)
            {
                PlayerSave save = new PlayerSave();
                int seed = 1;
                Populate(save, ref seed, 0);
                GoldenFiles.Write("Saves/rich-v14.input.json", NewSerializer().Serialize(save));
            }

            return GoldenFiles.Read("Saves/rich-v14.input.json");
        }

        [Test]
        public void RichV14_RoundTripsByteIdentical()
        {
            string input = RichV14();
            SaveLoadResult result = NewSerializer().Deserialize(input);

            Assert.IsTrue(result.Success, result.Error);
            Assert.IsFalse(result.Migrated);
            Assert.AreEqual(input, NewSerializer().Serialize(result.Save), "a current-schema save must write back exactly as read");
            StringAssert.Contains("\"Difficulty\":", input, "the rich save fills the schema-6 field");
            StringAssert.Contains("\"SeenHintIds\":[", input, "the rich save fills the schema-7 fields");
            StringAssert.Contains("\"ClaimedKinshipIds\":[", input, "the rich save fills the schema-8 account-wide fields");
            StringAssert.Contains("\"DiscoverySeed\":", input, "the rich save fills the schema-8 region fields");
            StringAssert.Contains("\"KinshipJoins\":[", input, "the rich save fills the schema-9 Kinship join records");
            StringAssert.Contains("\"EarnedIds\":[", input, "the rich save fills the schema-9 achievements");
            StringAssert.Contains("\"LookTokens\":", input, "the rich save fills the schema-9 look tokens");
            StringAssert.Contains("\"HabitatsUnlocked\":[", input, "the rich save fills the schema-10 Grove fields");
            StringAssert.Contains("\"Plots\":[", input, "the rich save fills the schema-10 Garden fields");
            StringAssert.Contains("\"StoriesUnlocked\":[", input, "the rich save fills the schema-10 Expeditions fields");
            StringAssert.Contains("\"LinesSeen\":[", input, "the rich save fills the schema-10 NPC dialogue layer's fields (D2)");
            StringAssert.Contains("\"RequestsFulfilled\":[", input, "the rich save fills the schema-10 NPC dialogue layer's fields (D2)");
            StringAssert.Contains("\"ChaptersCompleted\":[", input, "the rich save fills the schema-10 NPC dialogue layer's fields (D2)");
            StringAssert.Contains("\"LocationsSoothed\":", input, "the rich save fills the schema-10 peaceful-clears field (D3)");
            StringAssert.Contains("\"PendingBattleConsumables\":[\"", input, "the rich save fills the schema-11 crash-refund field");
            StringAssert.Contains("\"Seen\":{\"Gear\":[\"", input, "the rich save fills the schema-12 seen list");
            StringAssert.Contains("\"PreferredDifficulty\":1", input, "the rich save fills the schema-12 difficulty preference");
            StringAssert.Contains("\"NodeRetreats\":", input, "the rich save fills the schema-13 retreat-tracking field");
            StringAssert.Contains("\"NodeRetreatsNodeId\":", input, "the rich save fills the schema-13 retreat-tracking field");
            StringAssert.Contains("\"ReachedBackdropIds\":[\"", input, "the rich save fills the schema-14 backdrop picker field");
            StringAssert.Contains("\"SelectedBackdropId\":\"", input, "the rich save fills the schema-14 backdrop picker field");
        }

        [TestCase(1)]
        [TestCase(2)]
        [TestCase(3)]
        [TestCase(4)]
        [TestCase(5)]
        [TestCase(6)]
        [TestCase(7)]
        [TestCase(8)]
        [TestCase(9)]
        [TestCase(10)]
        [TestCase(11)]
        [TestCase(12)]
        [TestCase(13)]
        [TestCase(14)]
        public void RichSave_LoadsAndMigrates_ToTheGoldenText(int version)
        {
            string input = version == 14 ? RichV14()
                            : version == 13 ? RichV13()
                            : version == 12 ? RichV12()
                            : version == 11 ? RichV11()
                            : version == 10 ? RichV10()
                            : version == 9 ? RichV9()
                            : version == 8 ? RichV8()
                            : version == 7 ? RichV7()
                            : version == 6 ? RichV6()
                            : RichV5().Replace("\"SchemaVersion\":5", "\"SchemaVersion\":" + version);
            AssertGolden("rich-v" + version, input, version);
        }

        [TestCase(1)]
        [TestCase(2)]
        [TestCase(3)]
        [TestCase(4)]
        [TestCase(5)]
        [TestCase(6)]
        [TestCase(7)]
        [TestCase(8)]
        [TestCase(9)]
        [TestCase(10)]
        [TestCase(11)]
        [TestCase(12)]
        [TestCase(13)]
        [TestCase(14)]
        public void MinimalSave_LoadsAndMigrates_ToTheGoldenText(int version)
        {
            AssertGolden("min-v" + version, MinimalInputs[version - 1], version);
        }

        [Test]
        public void PlayerSettings_RoundTripToTheGoldenText()
        {
            JsonSaveSerializer json = new JsonSaveSerializer();
            PlayerSettings settings = json.FromJson<PlayerSettings>("{\"SchemaVersion\":1,\"TeamSuggestionsEnabled\":false,\"Unknown\":3}");

            GoldenFiles.AssertMatches("Saves/settings.expected.json", json.ToJson(settings) + "\n" + json.ToJson(new PlayerSettings()));
        }

        private static void AssertGolden(string name, string input, int version)
        {
            SaveLoadResult result = NewSerializer().Deserialize(input);

            Assert.IsTrue(result.Success, result.Error);
            Assert.AreEqual(version, result.SourceVersion);
            Assert.AreEqual(version < PlayerSave.CurrentSchemaVersion, result.Migrated);

            string output = NewSerializer().Serialize(result.Save);
            GoldenFiles.AssertMatches("Saves/" + name + ".expected.json", output);

            // Written text reads back to itself: the saved form is a fixed point.
            SaveLoadResult again = NewSerializer().Deserialize(output);
            Assert.IsTrue(again.Success, again.Error);
            Assert.AreEqual(output, NewSerializer().Serialize(again.Save));
        }

        // ---- Deterministic fill of every serialized field (used only to capture the rich saves) ----

        private static void Populate(object target, ref int seed, int depth)
        {
            foreach (FieldInfo field in target.GetType().GetFields(BindingFlags.Public | BindingFlags.Instance))
            {
                if (field.IsInitOnly || field.IsDefined(typeof(NonSerializedAttribute), true))
                {
                    continue;
                }

                object value = Make(field.FieldType, ref seed, depth + 1);
                if (target is Grove.PlacedDecorEntry && value is float fraction)
                {
                    // Decor sits at fractions of its habitat canvas (0-1, clamped on load since schema 12).
                    value = (float)Math.Round(fraction / 100f, 4);
                }

                if (value != null)
                {
                    field.SetValue(target, value);
                }
            }
        }

        private static object Make(Type type, ref int seed, int depth)
        {
            if (depth > 12)
            {
                return null;
            }

            if (type == typeof(string))
            {
                return "s" + seed++;
            }

            if (type == typeof(int))
            {
                return seed++;
            }

            if (type == typeof(long))
            {
                return 1700000000000L + seed++;
            }

            if (type == typeof(float))
            {
                return (seed++ * 0.25f) + 0.1f;
            }

            if (type == typeof(double))
            {
                return (seed++ * 0.25) + 0.1;
            }

            if (type == typeof(bool))
            {
                return seed++ % 2 == 0;
            }

            if (type.IsEnum)
            {
                Array values = Enum.GetValues(type);
                return values.GetValue(seed++ % values.Length);
            }

            if (type.IsArray)
            {
                Type element = type.GetElementType();
                Array array = Array.CreateInstance(element, 2);

                for (int i = 0; i < 2; i++)
                {
                    array.SetValue(Make(element, ref seed, depth + 1), i);
                }

                return array;
            }

            if (type.IsGenericType && type.GetGenericTypeDefinition() == typeof(List<>))
            {
                Type element = type.GetGenericArguments()[0];
                IList list = (IList)Activator.CreateInstance(type);

                for (int i = 0; i < 2; i++)
                {
                    list.Add(Make(element, ref seed, depth + 1));
                }

                return list;
            }

            bool ours = type.Namespace != null && type.Namespace.StartsWith("BeastCraft", StringComparison.Ordinal);
            bool colour = type.Name == "Color";

            if ((ours || colour) && (type.IsValueType || type.GetConstructor(Type.EmptyTypes) != null))
            {
                object instance = Activator.CreateInstance(type);
                Populate(instance, ref seed, depth);
                return instance;
            }

            return null;
        }
    }
}
