using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using BeastCraft.Battle;
using BeastCraft.Campaign;
using BeastCraft.Creatures;
using BeastCraft.Encounters;

namespace BeastCraft.Tooling.BalanceSim
{
    /// <summary>
    /// <c>--mode assistfloor</c>: the adaptive-assist floor per kind of fight (<c>regions.json</c>
    /// <c>AssistFloorScales</c>, one scale per shape or <c>boss</c>; producer decision "assist +
    /// guidance", see docs/balance/tuning-log.md, "Never-blocked targets"). Each consecutive loss at
    /// a location eases that fight further (<see cref="BeastCraft.Campaign.RegionLibrary.AssistScaleFor"/>,
    /// a step per loss, compounding) down to this floor, chosen so the owned-roster WEAK pick
    /// (<see cref="TypicalTeamModel"/>, the same population <c>--mode typical</c> calibrates on)
    /// reaches <see cref="MainTarget"/>% for an ordinary fight or <see cref="BossTarget"/>% for a
    /// region boss, at the floor.
    /// <para>
    /// <strong>Multiple levels, one scale.</strong> The floor is one flat scale per shape (as the
    /// early-region easing already is), but the weak pick's shortfall is not flat across levels (it
    /// gets much worse once the whole roster is owned): calibrated at every <see cref="Levels"/> for
    /// the ordinary shapes and every region's own boss (its own level, mainline and post-game Normal;
    /// post-game Hard is never assisted so it is not calibrated), the SHIPPED scale is the minimum
    /// (strongest discount) needed across them, so the target is met everywhere, not just at the
    /// worst level — the report lists every level's own need and which one was binding.
    /// </para>
    /// <para>
    /// <strong>Expected attempts to clear</strong> (the weak pick at equal level, assist on): from the
    /// shipping (no-assist) weak rate and the floor rate, interpolated linearly over the losses it
    /// takes <see cref="BeastCraft.Campaign.RegionLibrary.AssistScaleFor"/> to reach the floor (then
    /// constant), a closed form for the expected number of attempts to first clear — no extra
    /// simulation. An approximation (the true curve need not be linear between the two measured
    /// points) but the right order of magnitude to check the producer's "&lt;= 3 ordinary, &lt;= 5
    /// boss" bar.
    /// </para>
    /// </summary>
    public static class AssistFloorCalibration
    {
        /// <summary>The weak pick's target at the floor for an ordinary fight (solo/elite/squad/horde).</summary>
        public const double MainTarget = 70.0;

        /// <summary>The weak pick's target at the floor for a region boss (scaled with a lower-target boss, e.g. post-game Normal: <see cref="BossFloorTarget"/>).</summary>
        public const double BossTarget = 60.0;

        /// <summary>The levels the ordinary-shape floor is checked at (the owned roster is full from 60 on; see the class notes).</summary>
        public static readonly int[] Levels = { 10, 30, 50, 70, 90 };

        /// <summary>The assist step this run assumes (<c>regions.json</c> <c>AssistStep</c>, about -10% a loss), for the expected-attempts estimate.</summary>
        public const double AssumedStep = 0.10;

        public static int Run(SimOptions options, List<CreatureSpeciesSO> species, Dictionary<string, GrowthRateCurve> curves)
        {
            TypicalCalibration.Context context = TypicalCalibration.BuildContext(options, species, curves, out EncounterCatalog catalog, out List<string> errors);
            if (context == null)
            {
                Console.Error.WriteLine("Could not read the content:");
                foreach (string error in errors)
                {
                    Console.Error.WriteLine("  " + error);
                }

                return 2;
            }

            int samples = options.TypicalSamples;
            StringBuilder sb = new StringBuilder();
            sb.Append("# Beast Craft adaptive-assist floor\n\n");
            sb.Append("Generated by `dotnet run --project Tooling/BalanceSim -c Release -- --mode assistfloor`\n");
            sb.Append("(see Tooling/BalanceSim/README.md, \"Adaptive assist floor\"). Per shape, the multiplier (as a scale on the shipping table) at\n");
            sb.Append("which the WEAK owned-roster pick (`--mode typical`'s population) reaches ").Append(SimOptions.Format(MainTarget))
              .Append("% (a region boss ").Append(SimOptions.Format(BossTarget)).Append("%), at every level in\n");
            sb.Append("`--levels ").Append(string.Join(",", Array.ConvertAll(Levels, l => l.ToString(CultureInfo.InvariantCulture)))).Append("` and every region's own boss; the shipped scale is the minimum (strongest discount) needed, so the\n");
            sb.Append("target is met everywhere, not just at the level it binds. Also the expected attempts to clear at equal level, assist on\n");
            sb.Append("(assumed step ").Append(AssumedStep.ToString("0.00", CultureInfo.InvariantCulture)).Append(" = -").Append((AssumedStep * 100).ToString("0", CultureInfo.InvariantCulture))
              .Append("% a loss): the producer's bar is <= 3 for an ordinary fight, <= 5 for a boss.\n\n");

            sb.Append("## Ordinary shapes\n\n");
            sb.Append("| Shape | Level | Shipping | Weak (no assist) | Floor mult. | Scale needed | Weak at floor |\n");
            sb.Append("| --- | ---: | ---: | ---: | ---: | ---: | ---: |\n");

            Dictionary<string, double> minScale = new Dictionary<string, double>(StringComparer.Ordinal);
            Dictionary<string, (int level, double scale, double r0, double weakAtFloor)> binding = new Dictionary<string, (int, double, double, double)>(StringComparer.Ordinal);
            foreach (EncounterShape shape in catalog.Shapes)
            {
                if (!context.Before.HasShape(shape.Id))
                {
                    continue;
                }

                foreach (int level in Levels)
                {
                    int skillLevel = context.Skills.Typical(level);
                    PveSimulator pve = context.Simulator(skillLevel, options.ObstaclesRegion);
                    TypicalTeamModel.Band band = context.Model.BandAt(level);
                    double shipping = context.Before.Multiplier(shape.Id, level);
                    double r0 = context.Model.Evaluate(pve, band, shape, shipping, samples).Weak;
                    double floorMult = TypicalCalibration.Search(MainTarget, m => context.Model.Evaluate(pve, band, shape, m, samples).Weak);
                    double weakAtFloor = context.Model.Evaluate(pve, band, shape, floorMult, samples).Weak;
                    double scale = shipping > 0.0 ? Math.Min(1.0, floorMult / shipping) : 1.0;

                    sb.Append("| `").Append(shape.Id).Append("` | ").Append(level).Append(" | x").Append(SimOptions.FormatMultiplier(shipping)).Append(" | ")
                      .Append(SimOptions.Format(r0)).Append("% | x").Append(SimOptions.FormatMultiplier(floorMult)).Append(" | ")
                      .Append(scale.ToString("0.000", CultureInfo.InvariantCulture)).Append(" | ").Append(SimOptions.Format(weakAtFloor)).Append("% |\n");
                    Console.Error.WriteLine("Assist floor " + shape.Id + "/L" + level + ": shipping x" + SimOptions.FormatMultiplier(shipping) + " (weak " +
                                            SimOptions.Format(r0) + "%), floor x" + SimOptions.FormatMultiplier(floorMult) + " (scale " +
                                            scale.ToString("0.000", CultureInfo.InvariantCulture) + "), weak at floor " + SimOptions.Format(weakAtFloor) + "%.");

                    if (!minScale.TryGetValue(shape.Id, out double best) || scale < best)
                    {
                        minScale[shape.Id] = scale;
                        binding[shape.Id] = (level, scale, r0, weakAtFloor);
                    }
                }
            }

            sb.Append("\n### Shipped scale (minimum across levels)\n\n");
            sb.Append("| Shape | Scale | Binding level | Expected attempts (equal level, assist on) |\n");
            sb.Append("| --- | ---: | ---: | ---: |\n");
            foreach (KeyValuePair<string, double> entry in minScale)
            {
                (int level, double scale, double r0, double weakAtFloor) bind = binding[entry.Key];
                // The rate actually reached at the shipped floor (weakAtFloor), not the aspirational
                // target: the search's bisection resolution can overshoot it (see the boss loop below,
                // where this can matter a lot), and expected attempts should reflect what really happens.
                double attempts = ExpectedAttempts(bind.r0, bind.weakAtFloor, entry.Value, AssumedStep);
                sb.Append("| `").Append(entry.Key).Append("` | ").Append(entry.Value.ToString("0.000", CultureInfo.InvariantCulture)).Append(" | ").Append(bind.level)
                  .Append(" | ").Append(attempts.ToString("0.00", CultureInfo.InvariantCulture)).Append(attempts <= 3.0 ? " (meets <= 3)" : " **(over 3)**").Append(" |\n");
                Console.Error.WriteLine("Shipped " + entry.Key + ": scale " + entry.Value.ToString("0.000", CultureInfo.InvariantCulture) + " (binding L" + bind.level +
                                        "), expected attempts " + attempts.ToString("0.00", CultureInfo.InvariantCulture) + ".");
            }

            sb.Append("\n## Region bosses\n\n");
            sb.Append("Each at its own level; target ").Append(SimOptions.Format(BossTarget)).Append("% (a post-game Normal boss scaled with its own typical target: BossTarget x typical / 75; post-game Hard is never assisted, not calibrated here).\n\n");
            sb.Append("| Boss | Region | Level | Target | Shipping | Weak (no assist) | Floor mult. | Scale needed | Weak at floor | Expected attempts |\n");
            sb.Append("| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |\n");

            double bossMinScale = double.MaxValue;
            string bossBindingId = null;
            foreach (RegionData region in context.Regions.Regions)
            {
                // Post-game Hard is a separate template (region.HardMode.BossTemplateId) and is never
                // assisted (CampaignRules.PlanFor), so it is not calibrated here; only this region's
                // Normal boss (region.BossTemplateId, mainline or post-game) is.
                string templateId = region.BossTemplateId;
                if (string.IsNullOrEmpty(templateId))
                {
                    continue;
                }

                EncounterPlan plan = EncounterPlan.FromTemplate(context.Library, context.Enemies, templateId, region.MaxLevel);
                if (plan == null)
                {
                    continue;
                }

                double typicalTarget = region.IsPostGame ? TypicalCalibration.PostGameBossNormal : TypicalCalibration.BossTarget;
                double target = BossTarget * typicalTarget / TypicalCalibration.BossTarget;

                EncounterShape shape = NewPlayerReport.TemplateShape(context.Enemies, plan);
                int skillLevel = context.Skills.Typical(region.MaxLevel);
                PveSimulator pve = context.Simulator(skillLevel, region.RegionId);
                TypicalTeamModel.Band band = context.Model.BandAt(region.MaxLevel);
                double r0 = context.Model.Evaluate(pve, band, shape, plan.Multiplier, samples).Weak;
                double floorMult = TypicalCalibration.Search(target, m => context.Model.Evaluate(pve, band, shape, m, samples).Weak);
                double weakAtFloor = context.Model.Evaluate(pve, band, shape, floorMult, samples).Weak;
                double scale = plan.Multiplier > 0.0 ? Math.Min(1.0, floorMult / plan.Multiplier) : 1.0;
                // As above: the rate actually reached at the floor (weakAtFloor), not the target.
                double attempts = ExpectedAttempts(r0, weakAtFloor, scale, AssumedStep);

                sb.Append("| `").Append(templateId).Append("` | ").Append(region.RegionId).Append(" | ").Append(region.MaxLevel).Append(" | ")
                  .Append(SimOptions.Format(target)).Append("% | x").Append(SimOptions.FormatMultiplier(plan.Multiplier)).Append(" | ").Append(SimOptions.Format(r0))
                  .Append("% | x").Append(SimOptions.FormatMultiplier(floorMult)).Append(" | ").Append(scale.ToString("0.000", CultureInfo.InvariantCulture)).Append(" | ")
                  .Append(SimOptions.Format(weakAtFloor)).Append("% | ").Append(attempts.ToString("0.00", CultureInfo.InvariantCulture))
                  .Append(attempts <= 5.0 ? " (meets <= 5)" : " **(over 5)**").Append(" |\n");
                Console.Error.WriteLine("Assist floor boss " + templateId + "/" + region.RegionId + ": shipping x" + SimOptions.FormatMultiplier(plan.Multiplier) +
                                        " (weak " + SimOptions.Format(r0) + "%), floor x" + SimOptions.FormatMultiplier(floorMult) + " (scale " +
                                        scale.ToString("0.000", CultureInfo.InvariantCulture) + "), expected attempts " + attempts.ToString("0.00", CultureInfo.InvariantCulture) + ".");

                if (!region.IsPostGame && scale < bossMinScale)
                {
                    bossMinScale = scale;
                    bossBindingId = templateId;
                }
            }

            if (bossBindingId != null)
            {
                sb.Append("\nShipped `boss` scale (minimum across the 10 mainline bosses, excluding post-game): ").Append(bossMinScale.ToString("0.000", CultureInfo.InvariantCulture))
                  .Append(" (binding: `").Append(bossBindingId).Append("`). Post-game Normal's own row above is its own need (r11's typical target is already lower, 35% not\n");
                sb.Append("75%, so folding it into the shared minimum would over-discount every mainline boss); ship it as a per-boss override if it needs one.\n");
                Console.Error.WriteLine("Shipped boss scale (mainline min): " + bossMinScale.ToString("0.000", CultureInfo.InvariantCulture) + " (binding " + bossBindingId + ").");
            }

            string reportText = sb.ToString().Replace("\r\n", "\n");
            Console.Out.Write(reportText);
            if (!string.IsNullOrEmpty(options.OutPath))
            {
                System.IO.File.WriteAllText(options.OutPath, reportText, new System.Text.UTF8Encoding(false));
                Console.Error.WriteLine("Report written to " + System.IO.Path.GetFullPath(options.OutPath));
            }

            return 0;
        }

        /// <summary>
        /// The expected number of attempts to first clear, assist on: attempt <c>n</c> (0-based, n
        /// losses so far) clears at a rate linearly interpolated from <paramref name="r0"/> (n=0, the
        /// shipping rate) to <paramref name="floorRate"/> (reached once
        /// <c>(1-step)^n &lt;= floorScale</c>, then constant). <c>E = sum over n of P(no clear in the
        /// first n attempts)</c>, the explicit ramp plus a geometric tail from the floor rate. An
        /// approximation (assumes the true rate is linear between the two measured points, R0 and the
        /// floor); not a simulation.
        /// </summary>
        public static double ExpectedAttempts(double r0Percent, double floorRatePercent, double floorScale, double step)
        {
            double r0 = Math.Max(0.0001, Math.Min(1.0, r0Percent / 100.0));
            double floorRate = Math.Max(0.0001, Math.Min(1.0, floorRatePercent / 100.0));
            if (floorScale >= 1.0 || step <= 0.0)
            {
                return 1.0 / r0;
            }

            // Losses to reach the floor scale, compounding (1 - step) each time: R_0 = r0 (no losses
            // yet), R_i (0 < i < nFloor) linearly interpolated toward floorRate, R_i = floorRate from
            // nFloor on.
            int nFloor = Math.Max(1, (int)Math.Ceiling(Math.Log(floorScale, 1.0 - step)));
            double[] rate = new double[nFloor + 1];
            rate[0] = r0;
            for (int i = 1; i <= nFloor; i++)
            {
                rate[i] = r0 + ((floorRate - r0) * i / nFloor);
            }

            // Attempt k (1-based) sees rate[min(k-1, nFloor)] (0 losses yet for attempt 1, etc.).
            // E[attempts] = sum over k>=1 of P(fail attempts 1..k-1); the explicit ramp, then a
            // geometric tail once every remaining attempt sees the constant floor rate.
            double survival = 1.0;
            double expected = 0.0;
            for (int k = 1; k <= nFloor; k++)
            {
                expected += survival;
                survival *= 1.0 - rate[k - 1];
            }

            expected += survival / floorRate;
            return expected;
        }
    }
}
