using System.Collections.Generic;
using System.Globalization;
using System.Text;
using BeastCraft.Battle;
using BeastCraft.Creatures;

namespace BeastCraft.Tooling.BalanceSim
{
    /// <summary>
    /// Assembles the whole Markdown report: header, the shared standard kit, the PvE section
    /// (primary), the PvP section (secondary) and the assembled-stats table. Contains no timestamps,
    /// machine paths or timings, so two runs are byte-identical.
    /// </summary>
    public static class Report
    {
        public static string Build(SimOptions options, IReadOnlyList<CreatureSpeciesSO> species, List<Encounter> encounters, PveSimulator pve,
                                   List<PveCell> cells, List<BattleRecord> pvpRecords)
        {
            StringBuilder report = new StringBuilder();

            report.AppendLine("# Beast Craft balance simulator report");
            report.AppendLine();
            report.AppendLine("Generated by `Tooling/BalanceSim` (local-only tooling, not a CI job). These numbers are inputs to design");
            report.AppendLine("decisions; nothing here is applied to the roster automatically. The run is deterministic: the same roster,");
            report.AppendLine("fixtures, code and arguments produce a byte-identical report.");
            report.AppendLine();
            report.AppendLine("- Roster: `" + RosterLoader.RepoRelativePath + "` (" + species.Count + " species)");
            report.AppendLine("- Sections: " + (options.RunPve ? "PvE team vs encounter (primary)" : string.Empty) +
                              (options.RunPve && options.RunPvp ? "; " : string.Empty) + (options.RunPvp ? "PvP 1v1 round-robin (secondary)" : string.Empty));
            report.AppendLine();

            AppendKit(report);

            if (options.RunPve)
            {
                PveReport.AppendSection(report, options, species, encounters, pve, cells);
            }

            if (options.RunPvp)
            {
                PvpReport.AppendSection(report, options, species, pvpRecords);
            }

            AppendStats(report, options, species);
            return report.ToString();
        }

        private static void AppendKit(StringBuilder report)
        {
            report.AppendLine("## Standard beast kit");
            report.AppendLine();
            report.AppendLine("No skills are authored yet, so every beast fights with the same kit and its stat line is what gets measured.");
            report.AppendLine("Fire priority is the order below; every skill aims at the nearest enemy.");
            report.AppendLine();
            report.AppendLine("| Skill | Category | Shape | Range | Power | Cooldown |");
            report.AppendLine("| --- | --- | --- | ---: | ---: | ---: |");
            report.AppendLine("| Blast | " + SimOptions.BlastCategory + " | SingleTarget | " + SimOptions.BlastRange + " | " + Number(SimOptions.BlastPower) + " | " +
                              SimOptions.BlastCooldown + " |");
            report.AppendLine("| Strike | " + SimOptions.StrikeCategory + " | SingleTarget | " + SimOptions.StrikeRange + " | " + Number(SimOptions.StrikePower) +
                              " | " + SimOptions.StrikeCooldown + " |");
            report.AppendLine("| Burst (physical half) | " + DamageCategory.Physical + " | AreaBurst (radius " + SimOptions.BurstRadius + " around the caster) | " +
                              SimOptions.BurstRadius + " | " + Number(SimOptions.BurstPower) + " | " + SimOptions.BurstCooldown + " |");
            report.AppendLine("| Burst (special half) | " + DamageCategory.Special + " | AreaBurst (radius " + SimOptions.BurstRadius + " around the caster) | " +
                              SimOptions.BurstRadius + " | " + Number(SimOptions.BurstPower) + " | " + SimOptions.BurstCooldown + " |");
            report.AppendLine();
            report.AppendLine("Strike and Blast share a cooldown; Strike's higher power offsets its range-1 handicap (it fires about 0.73x as");
            report.AppendLine("often as Blast), and Burst is split into equal physical and special halves, so `Attack` and `SpecialAttack` (and");
            report.AppendLine("`Defense` / `SpecialDefense` on the receiving end) carry about equal weight; the PvE kit parity table checks it.");
            report.AppendLine("Burst goes last so it fires from the tile the beast has just walked to. `elemental` mode: every kit skill carries");
            report.AppendLine("the beast's first element; `neutral`: all are `None`, isolating the stat lines from the element chart.");
            report.AppendLine();
        }

        private static void AppendStats(StringBuilder report, SimOptions options, IReadOnlyList<CreatureSpeciesSO> species)
        {
            report.AppendLine("## Assembled stats at level " + options.MatrixLevel);
            report.AppendLine();
            report.AppendLine("From `StatCalculator.ComputeStats` with no gear — what each beast actually fought with at that level.");
            report.AppendLine();
            report.AppendLine("| Beast | Element | Stance | HP | Atk | Def | SpA | SpD | Spe | Move |");
            report.AppendLine("| --- | --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |");

            foreach (CreatureSpeciesSO beast in species)
            {
                StatBlock stats = StatCalculator.ComputeStats(beast, options.MatrixLevel, null);
                report.AppendLine("| " + beast.DisplayName + " | " + PvpReport.ElementsOf(beast) + " | " + beast.Stance + " | " + stats.Hp + " | " + stats.Attack + " | " + stats.Defense +
                                  " | " + stats.SpecialAttack + " | " + stats.SpecialDefense + " | " + stats.Speed + " | " + stats.MoveRange + " |");
            }
        }

        private static string Number(float value)
        {
            return value.ToString(CultureInfo.InvariantCulture);
        }
    }
}
