using System.Collections.Generic;
using System.Globalization;
using System.Text;
using BeastCraft.Battle;
using BeastCraft.Creatures;

namespace BeastCraft.Tooling.BalanceSim
{
    /// <summary>
    /// Assembles the whole Markdown report: header, the shared standard kit, the PvE section
    /// (primary), the PvP section (secondary) and the assembled-stats table. Contains no timestamps,
    /// machine paths or timings, so two runs are byte-identical.
    /// </summary>
    public static class Report
    {
        public static string Build(SimOptions options, IReadOnlyList<CreatureSpeciesSO> species, EncounterCatalog encounters, PveSimulator pve,
                                   List<PveCell> cells, List<BattleRecord> pvpRecords)
        {
            StringBuilder report = new StringBuilder();

            report.AppendLine("# Beast Craft balance simulator report");
            report.AppendLine();
            report.AppendLine("Generated by `Tooling/BalanceSim` (local-only tooling, not a CI job). These numbers are inputs to design");
            report.AppendLine("decisions; nothing here is applied to the roster automatically. Battles are random (damage variance and crits),");
            report.AppendLine("but every battle's rng is seeded from the inputs, so the run is deterministic: the same roster, fixtures, code");
            report.AppendLine("and arguments produce a byte-identical report. Battles per PvE team and " +
                              (options.EncounterSet == EncounterSet.Generated ? "composition" : "encounter") + ": " + options.PveSamples + "; per PvP game: " +
                              options.Samples + " (`--samples`), each with its own seed.");
            report.AppendLine();
            report.AppendLine("- Roster: `" + RosterLoader.RepoRelativePath + "` (" + species.Count + " species)");
            report.AppendLine("- Sections: " + (options.RunPve ? "PvE team vs encounter (primary)" : string.Empty) +
                              (options.RunPve && options.RunPvp ? "; " : string.Empty) + (options.RunPvp ? "PvP 1v1 round-robin (secondary)" : string.Empty));
            report.AppendLine();

            AppendKit(report);

            if (options.RunPve)
            {
                PveReport.AppendSection(report, options, species, encounters, pve, cells);
            }

            if (options.RunPvp)
            {
                PvpReport.AppendSection(report, options, species, pvpRecords);
            }

            AppendStats(report, options, species);
            return report.ToString();
        }

        private static void AppendKit(StringBuilder report)
        {
            report.AppendLine("## Standard beast kit");
            report.AppendLine();
            report.AppendLine("No skills are authored yet, so every beast fights with the same kit and its stat line is what gets measured.");
            report.AppendLine("Fire priority is the order below; every skill aims at the nearest enemy. The physical single-target skill depends on");
            report.AppendLine("the beast's stance: Strike for Vanguard and Skirmisher beasts, Shot for Ranged beasts (which never walk into melee).");
            report.AppendLine();
            report.AppendLine("| Skill | Category | Shape | Range | Power | Cooldown |");
            report.AppendLine("| --- | --- | --- | ---: | ---: | ---: |");
            report.AppendLine("| Blast | " + SimOptions.BlastCategory + " | SingleTarget | " + SimOptions.BlastRange + " | " + Number(SimOptions.BlastPower) + " | " +
                              SimOptions.BlastCooldown + " |");
            report.AppendLine("| Strike (Vanguard, Skirmisher) | " + SimOptions.StrikeCategory + " | SingleTarget | " + SimOptions.StrikeRange + " | " +
                              Number(SimOptions.StrikePower) + " | " + SimOptions.StrikeCooldown + " |");
            report.AppendLine("| Shot (Ranged) | " + SimOptions.ShotCategory + " | SingleTarget | " + SimOptions.ShotRange + " | " + Number(SimOptions.ShotPower) +
                              " | " + SimOptions.ShotCooldown + " |");
            report.AppendLine("| Burst (physical half) | " + DamageCategory.Physical + " | AreaBurst (radius " + SimOptions.BurstRadius + " around the caster) | " +
                              SimOptions.BurstRadius + " | " + Number(SimOptions.BurstPower) + " | " + SimOptions.BurstCooldown + " |");
            report.AppendLine("| Burst (special half) | " + DamageCategory.Special + " | AreaBurst (radius " + SimOptions.BurstRadius + " around the caster) | " +
                              SimOptions.BurstRadius + " | " + Number(SimOptions.BurstPower) + " | " + SimOptions.BurstCooldown + " |");
            report.AppendLine();
            report.AppendLine("The physical skill and Blast share a cooldown; each physical skill's power offsets how much less often it fires than");
            report.AppendLine("Blast in its stance (Strike's range-1 handicap; Shot fires after Blast and loses the odd target Blast just felled),");
            report.AppendLine("and Burst is split into equal physical and special halves, so `Attack` and `SpecialAttack` (and `Defense` /");
            report.AppendLine("`SpecialDefense` on the receiving end) carry about equal weight in every stance; the PvE kit parity table checks it.");
            report.AppendLine("Burst goes last so it fires from the tile the beast has just walked to. `elemental` mode: every kit skill carries");
            report.AppendLine("the beast's first element; `neutral`: all are `None`, isolating the stat lines from the element chart.");
            report.AppendLine("Power is a percent of the attacking stat: a hit is `Power / 100 x A x A / (A + " +
                              DamageFormula.DefenseWeight.ToString("0.##", CultureInfo.InvariantCulture) + " x D) x " +
                              DamageFormula.GlobalScale.ToString("0.##", CultureInfo.InvariantCulture) + "`, then element, crit and variance (`DamageFormula`).");
            report.AppendLine();
        }

        private static void AppendStats(StringBuilder report, SimOptions options, IReadOnlyList<CreatureSpeciesSO> species)
        {
            report.AppendLine("## Assembled stats at level " + options.MatrixLevel);
            report.AppendLine();
            report.AppendLine("From `StatCalculator.ComputeStats` with no gear — what each beast actually fought with at that level. **Turn rate**");
            report.AppendLine("= `TurnManager.FillRateForSpeed(Spe)` / the Speed-" + TurnManager.ReferenceSpeed + " rate: its turns per unit of normalized time (about sqrt(Spe / " +
                              TurnManager.ReferenceSpeed + ")).");
            report.AppendLine();
            report.AppendLine("| Beast | Element | Stance | HP | Atk | Def | SpA | SpD | Spe | Turn rate | Move | Crit |");
            report.AppendLine("| --- | --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |");

            foreach (CreatureSpeciesSO beast in species)
            {
                StatBlock stats = StatCalculator.ComputeStats(beast, options.MatrixLevel, null);
                report.AppendLine("| " + beast.DisplayName + " | " + PvpReport.ElementsOf(beast) + " | " + beast.Stance + " | " + stats.Hp + " | " + stats.Attack + " | " + stats.Defense +
                                  " | " + stats.SpecialAttack + " | " + stats.SpecialDefense + " | " + stats.Speed + " | " +
                                  ((double)TurnManager.FillRateForSpeed(stats.Speed) / TurnManager.ReferenceFillRate).ToString("0.000", CultureInfo.InvariantCulture) +
                                  " | " + stats.MoveRange + " | " +
                                  stats.CritChance + "% |");
            }
        }

        private static string Number(float value)
        {
            return value.ToString(CultureInfo.InvariantCulture);
        }
    }
}
