using System.Collections.Generic;
using System.Globalization;
using System.Text;
using BeastCraft.Battle;
using BeastCraft.Creatures;

namespace BeastCraft.Tooling.BalanceSim
{
    /// <summary>
    /// Assembles the whole Markdown report: header, the shared standard kit, the PvE section
    /// (primary), the PvP section (secondary) and the assembled-stats table. Contains no timestamps,
    /// machine paths or timings, so two runs are byte-identical.
    /// </summary>
    public static class Report
    {
        public static string Build(SimOptions options, IReadOnlyList<CreatureSpeciesSO> species, EncounterCatalog encounters, PveSimulator pve,
                                   List<PveCell> cells, List<BattleRecord> pvpRecords)
        {
            StringBuilder report = new StringBuilder();

            report.AppendLine("# Beast Craft balance simulator report");
            report.AppendLine();
            report.AppendLine("Generated by `Tooling/BalanceSim` (local-only tooling, not a CI job). These numbers are inputs to design");
            report.AppendLine("decisions; nothing here is applied to the roster automatically. Battles are random (damage variance and crits),");
            report.AppendLine("but every battle's rng is seeded from the inputs, so the run is deterministic: the same roster, fixtures, code");
            report.AppendLine("and arguments produce a byte-identical report. Battles per PvE team and " +
                              (options.EncounterSet == EncounterSet.Generated ? "composition" : "encounter") + ": " + options.PveSamples + "; per PvP game: " +
                              options.Samples + " (`--samples`), each with its own seed.");
            report.AppendLine();
            report.AppendLine("- Roster: `" + RosterLoader.RepoRelativePath + "` (" + species.Count + " species)");
            report.AppendLine("- Sections: " + (options.RunPve ? "PvE team vs encounter (primary)" : string.Empty) +
                              (options.RunPve && options.RunPvp ? "; " : string.Empty) + (options.RunPvp ? "PvP 1v1 round-robin (secondary)" : string.Empty));
            if (options.RunPve && pve != null && pve.Avatar.Enabled)
            {
                report.AppendLine("- Avatar (PvE only): the `" + pve.Avatar.Preset + "` " + (pve.Avatar.IsAuthored ? "preset (the skill library's default loadout, " : "fixture preset (") +
                                  "`--avatar`), fielded beside every player team; see \"Avatar passives\"");
            }

            if (options.KitSource == KitSource.Library)
            {
                report.AppendLine("- Skill kit: `library` (`--skill-kit library`, the default): each beast's authored default loadout from `" +
                                  SkillLibraryKits.RepoRelativePath + "` at skill level " + options.SkillLevel + " (`--skill-level`)");
                report.AppendLine(options.BondsActive
                    ? "- Team bonds: on (`--bonds on`, the default): the library's " + options.Library.TeamBonds.Count +
                      " `TeamBonds` apply at battle start to every player team that meets their condition (never to enemies); see \"PvE team bonds\""
                    : "- Team bonds: off (`--bonds off`)");
                if (options.Gear != GearProfile.None)
                {
                    report.AppendLine("- Gear (PvE): `--gear " + options.Gear.ToString().ToLowerInvariant() + "`: every player beast wears three pieces of the encounter level's band " +
                                      "from `gear-library.json` (GearKits); the default and the balance guard are gearless");
                }
            }
            else
            {
                report.AppendLine("- Skill kit: `standard` (`--skill-kit standard`): the same kit for every beast, so the stat lines are what is measured");
            }

            if (ScoutedPicker.Active(options))
            {
                List<string> strategies = new List<string>();
                for (int k = 0; k < ScoutedPicker.StrategyCount; k++)
                {
                    if (ScoutedPicker.Runs(options, k))
                    {
                        strategies.Add(ScoutedPicker.StrategyNames[k].ToLowerInvariant());
                    }
                }

                report.AppendLine("- Scouted picking (PvE, `--scouted`): " + string.Join(", ", strategies) + " at preview detail `" +
                                  SimOptions.DetailName(options.ScoutedDetail) + "`; post-processing of the same battles, see \"PvE scouted picking\"");
            }

            if (options.RunPve && options.CalibratesOnPick)
            {
                report.AppendLine("- Difficulty (PvE, `--calibrate-on " + SimOptions.CalibrationName(options.EffectiveCalibrateOn) + "`): calibrated so the team the " +
                                  PveReport.PickerName(options) + " fields per composition clears " + options.TargetSummary(encounters.Shapes) +
                                  (options.UniformTarget ? " (`--target-clear`)" : " (the shapes' `TargetClear`)") +
                                  " (the player scouts and counter-picks); the average team's no-scouting rate is reported beside it, see \"Calibrated difficulty\"");
            }

            if (options.RunPve && options.PinDifficultyPath != null)
            {
                report.AppendLine("- Difficulty pinned (PvE, `--pin-difficulty " + options.PinDifficultyPath + "`): no calibration search; every cell fights at " +
                                  "that table's multiplier, so \"Calibrated difficulty\" shows the clear rates at a stale calibration");
            }

            if (options.RunPve && options.LevelGaps != null)
            {
                report.AppendLine("- Level gap (PvE, `--level-gap`): every cell also replayed with the enemies " + SimOptions.Join(options.LevelGaps) +
                                  " levels above the team at its calibrated multiplier; see \"PvE level gap\"");
            }

            if (options.GapMixActive)
            {
                report.AppendLine("- Level-gap mix (PvE, `--gap-mix`): the balance sections (marginals, niches, flags, element matchups, team composition,");
                report.AppendLine("  bonds) are judged over battles at a mix of level gaps (" + options.GapMixText + "); calibration and scouting stay at gap 0;");
                report.AppendLine("  see \"Level-gap mix\"");
            }

            if (options.RunPve && options.PanelActive)
            {
                report.AppendLine("- Composition panel (PvE, `--panel " + options.PanelCompositions + "x" + options.PanelSamples + "`): every team against a fixed panel of " +
                                  options.PanelCompositions + " compositions per shape, " + options.PanelSamples + " times each, at level " + options.PanelLevel +
                                  "; see \"PvE composition panel\"");
            }

            if (options.RunPve && options.AvatarValue)
            {
                report.AppendLine("- Avatar value (PvE, `--avatar-value`): every cell's picked-team battles also replayed without the avatar; see \"PvE avatar value\"");
            }

            if (options.RunPve && options.TurnDetail)
            {
                report.AppendLine("- Beast turns (PvE, `--turn-detail`): no-fire turns and damage to large enemies per beast; see \"PvE beast turns\"");
            }

            report.AppendLine();

            if (options.KitSource == KitSource.Library)
            {
                AppendLibraryKit(report, options, species);
            }
            else
            {
                AppendKit(report);
            }

            if (options.RunPve)
            {
                PveReport.AppendSection(report, options, species, encounters, pve, cells);
                AppendAvatar(report, options, pve, cells);
            }

            if (options.RunPvp)
            {
                PvpReport.AppendSection(report, options, species, pvpRecords);
            }

            AppendStats(report, options, species);
            return report.ToString();
        }

        private static void AppendKit(StringBuilder report)
        {
            report.AppendLine("## Standard beast kit");
            report.AppendLine();
            report.AppendLine("No skills are authored yet, so every beast fights with the same kit and its stat line is what gets measured.");
            report.AppendLine("Fire priority is the order below; every skill aims at the nearest enemy. The physical single-target skill depends on");
            report.AppendLine("the beast's stance: Strike for Vanguard and Skirmisher beasts, Shot for Ranged beasts (which never walk into melee).");
            report.AppendLine();
            report.AppendLine("| Skill | Category | Shape | Range | Power | Cooldown |");
            report.AppendLine("| --- | --- | --- | ---: | ---: | ---: |");
            report.AppendLine("| Blast | " + SimOptions.BlastCategory + " | SingleTarget | " + SimOptions.BlastRange + " | " + Number(SimOptions.BlastPower) + " | " +
                              SimOptions.BlastCooldown + " |");
            report.AppendLine("| Strike (Vanguard, Skirmisher) | " + SimOptions.StrikeCategory + " | SingleTarget | " + SimOptions.StrikeRange + " | " +
                              Number(SimOptions.StrikePower) + " | " + SimOptions.StrikeCooldown + " |");
            report.AppendLine("| Shot (Ranged) | " + SimOptions.ShotCategory + " | SingleTarget | " + SimOptions.ShotRange + " | " + Number(SimOptions.ShotPower) +
                              " | " + SimOptions.ShotCooldown + " |");
            report.AppendLine("| Burst (physical half) | " + DamageCategory.Physical + " | AreaBurst (radius " + SimOptions.BurstRadius + " around the caster) | " +
                              SimOptions.BurstRadius + " | " + Number(SimOptions.BurstPower) + " | " + SimOptions.BurstCooldown + " |");
            report.AppendLine("| Burst (special half) | " + DamageCategory.Special + " | AreaBurst (radius " + SimOptions.BurstRadius + " around the caster) | " +
                              SimOptions.BurstRadius + " | " + Number(SimOptions.BurstPower) + " | " + SimOptions.BurstCooldown + " |");
            report.AppendLine();
            report.AppendLine("The physical skill and Blast share a cooldown; each physical skill's power offsets how much less often it fires than");
            report.AppendLine("Blast in its stance (Strike's range-1 handicap; Shot fires after Blast and loses the odd target Blast just felled),");
            report.AppendLine("and Burst is split into equal physical and special halves, so `Attack` and `SpecialAttack` (and `Defense` /");
            report.AppendLine("`SpecialDefense` on the receiving end) carry about equal weight in every stance; the PvE kit parity table checks it.");
            report.AppendLine("Burst goes last so it fires from the tile the beast has just walked to. `elemental` mode: every kit skill carries");
            report.AppendLine("the beast's first element; `neutral`: all are `None`, isolating the stat lines from the element chart.");
            report.AppendLine("Power is a percent of the attacking stat: a hit is `Power / 100 x A x A / (A + " +
                              DamageFormula.DefenseWeight.ToString("0.##", CultureInfo.InvariantCulture) + " x D) x " +
                              DamageFormula.GlobalScale.ToString("0.##", CultureInfo.InvariantCulture) + "`, then element, crit and variance (`DamageFormula`).");
            report.AppendLine();
        }

        /// <summary>
        /// The <c>--skill-kit library</c> replacement for the standard kit table: each beast's default
        /// loadout in fire-priority order, with each skill's shape, range, cooldown and effects as
        /// fielded (at the run's skill level and implied tier).
        /// </summary>
        private static void AppendLibraryKit(StringBuilder report, SimOptions options, IReadOnlyList<CreatureSpeciesSO> species)
        {
            report.AppendLine("## Library beast kits");
            report.AppendLine();
            report.AppendLine("Every beast fights with its authored `DefaultLoadout` from the skill library, in slot (fire-priority) order, at skill");
            report.AppendLine("level " + options.SkillLevel + " and the tier that level implies. Effects are listed as authored (magnitudes before level scaling);");
            report.AppendLine("`neutral` mode forces every library skill's element to `None`. There is no kit parity table in this mode: the kits differ");
            report.AppendLine("by design.");
            report.AppendLine();
            report.AppendLine("| Beast | Stance | Slot | Skill | Shape | Range | Cooldown | Effects |");
            report.AppendLine("| --- | --- | ---: | --- | --- | ---: | ---: | --- |");
            foreach (CreatureSpeciesSO beast in species)
            {
                IReadOnlyList<string> ids = options.Library.DefaultLoadout(beast.SpeciesId);
                for (int i = 0; i < ids.Count; i++)
                {
                    SkillInstance skill = options.Library.Instance(options.Library.Skill(ids[i]));
                    report.AppendLine("| " + (i == 0 ? beast.DisplayName : string.Empty) + " | " + (i == 0 ? beast.Stance.ToString() : string.Empty) + " | " + (i + 1) +
                                      " | " + skill.Skill.DisplayName + " | " + skill.Skill.TargetShape + (skill.Skill.TargetSide == SkillTargetSide.Ally ? " (ally)" : string.Empty) +
                                      " | " + skill.Skill.Range + " | " + skill.EffectiveCooldown + " | " + DescribeEffects(skill.Effects) + " |");
                }
            }

            report.AppendLine();
        }

        /// <summary>A compact one-line description of an effect list, for the library kit table.</summary>
        public static string DescribeEffects(IReadOnlyList<SkillEffect> effects)
        {
            List<string> parts = new List<string>();
            foreach (SkillEffect e in effects)
            {
                string chance = e.Chance > 0 && e.Chance < SkillEffect.AlwaysChance ? " " + e.Chance + "%" : string.Empty;
                string turns = e.DurationTurns > 0 ? " " + e.DurationTurns + "t" : string.Empty;
                string stacks = e.MaxStacks > 1 ? " x" + e.MaxStacks + " stacks" : string.Empty;
                switch (e.EffectType)
                {
                    case SkillEffectType.Damage:
                        parts.Add("dmg " + Number(e.Magnitude) + (e.HitCount > 1 ? " x" + e.HitCount + " hits" : string.Empty) +
                                  (e.ExecuteBonusPercent > 0 ? " exec +" + e.ExecuteBonusPercent + "%" : string.Empty));
                        break;
                    case SkillEffectType.Heal:
                        parts.Add("heal " + Number(e.Magnitude));
                        break;
                    case SkillEffectType.BuffStat:
                    case SkillEffectType.DebuffStat:
                        parts.Add((e.EffectType == SkillEffectType.BuffStat ? "+" : "-") + Number(e.Magnitude) + (e.IsPercent ? "% " : " ") + e.AffectedStat + turns + chance + stacks);
                        break;
                    case SkillEffectType.Cleanse:
                        parts.Add("cleanse (Stun, DoT)" + chance);
                        break;
                    default:
                        parts.Add(e.Status + (e.Status == StatusType.Knockback ? " " + Number(e.Magnitude) : e.Magnitude > 0f ? " " + Number(e.Magnitude) : string.Empty) + turns +
                                  chance + stacks);
                        break;
                }
            }

            return string.Join("; ", parts);
        }

        /// <summary>A compact one-line description of a bond reaction (trigger, who acts, caps, effects), for the bond table.</summary>
        public static string DescribeReaction(BeastCraft.Bonds.BondReaction r)
        {
            if (r == null || !r.IsActive)
            {
                return string.Empty;
            }

            List<string> parts = new List<string> { "on " + r.Trigger };
            if (r.TriggerFilter != BeastCraft.Bonds.BondTriggerFilter.Any)
            {
                parts.Add("(" + r.TriggerFilter + ")");
            }

            parts.Add(r.Action == BeastCraft.Bonds.BondAction.Intercept ? "intercept" : "-> " + r.Target);
            if (r.Chance > 0 && r.Chance < SkillEffect.AlwaysChance)
            {
                parts.Add(r.Chance + "%");
            }

            if (r.Trigger == BeastCraft.Bonds.BondTrigger.AllyBelowHpPercent)
            {
                parts.Add("below " + r.HpThresholdPercent + "%");
            }

            if (r.Range > 0)
            {
                parts.Add("range " + r.Range);
            }

            if (r.Cooldown > 0)
            {
                parts.Add("cd " + r.Cooldown);
            }

            if (r.MaxPerMember > 0)
            {
                parts.Add(r.MaxPerMember + "/member");
            }

            if (r.MaxPerTriggerUnit > 0)
            {
                parts.Add(r.MaxPerTriggerUnit + "/ally");
            }

            if (r.MaxPerBattle > 0)
            {
                parts.Add(r.MaxPerBattle + "/battle");
            }

            if (r.ReactorOrder == BeastCraft.Bonds.BondReactorOrder.HealthiestFirst)
            {
                parts.Add("healthiest first");
            }

            string effects = DescribeEffects(r.Effects);
            return string.Join(" ", parts) + (effects.Length > 0 ? ": " + effects : string.Empty);
        }

        /// <summary>
        /// How often each of the fielded avatar's passives fired, averaged over every PvE battle at
        /// the calibrated difficulty. Nothing at all without <c>--avatar</c>, so the default report
        /// is unchanged.
        /// </summary>
        private static void AppendAvatar(StringBuilder report, SimOptions options, PveSimulator pve, List<PveCell> cells)
        {
            if (pve == null || !pve.Avatar.Enabled)
            {
                return;
            }

            IReadOnlyList<BeastCraft.Avatar.PassiveSkillSO> passives = pve.Avatar.Passives;
            long[] totals = new long[passives.Count];
            long battles = 0;
            long avatarTurns = 0;
            long avatarCasts = 0;
            long battleTicks = 0;
            foreach (PveCell cell in cells)
            {
                foreach (PveBattle battle in cell.Battles)
                {
                    battles++;
                    avatarTurns += battle.AvatarTurns;
                    avatarCasts += battle.AvatarCasts;
                    battleTicks += battle.ElapsedTicks;
                    for (int p = 0; p < totals.Length; p++)
                    {
                        totals[p] += battle.PassiveFirings[p];
                    }
                }
            }

            report.AppendLine("## Avatar passives");
            report.AppendLine();
            report.AppendLine(pve.Avatar.IsAuthored
                                  ? "The `" + pve.Avatar.Preset + "` preset is the skill library's default avatar loadout (actives: " + ActiveNames(pve.Avatar) + ")."
                                  : "The `" + pve.Avatar.Preset + "` preset is a simulator fixture for exercising the passive engine, not authored content.");
            report.AppendLine("Firings per battle are averaged over every PvE battle at its cell's calibrated difficulty (" + battles + " battles).");
            report.AppendLine();
            double time = (double)battleTicks / TurnManager.TicksPerTimeUnit;
            report.AppendLine("- Avatar level: " + (options.AvatarLevel > 0
                                                         ? options.AvatarLevel.ToString(CultureInfo.InvariantCulture) + " (`--avatar-level`)"
                                                         : "each battle's encounter level (`--avatar-level` unset)") +
                              "; its stats follow the medium curve (every combat stat " + AvatarPresets.StatAtMaxLevel + " and Speed " +
                              AvatarPresets.SpeedAtMaxLevel + " at level 100).");
            report.AppendLine("- Avatar turns (its own ATB gauge) per battle: " + Per(avatarTurns, battles) + " (" +
                              (time <= 0 ? 0.0 : avatarTurns / time).ToString("0.00", CultureInfo.InvariantCulture) +
                              " per unit of normalized time); active casts per battle: " + Per(avatarCasts, battles) + ".");
            report.AppendLine();
            report.AppendLine("| Passive | Trigger | Scope | Proc % | Max / battle | Cooldown | Firings per battle |");
            report.AppendLine("| --- | --- | --- | ---: | ---: | ---: | ---: |");
            for (int p = 0; p < passives.Count; p++)
            {
                BeastCraft.Avatar.PassiveSkillSO passive = passives[p];
                report.AppendLine("| " + passive.PassiveId + " | " + passive.Trigger + " | " + passive.TargetScope + " | " + passive.ProcChance + " | " +
                                  (passive.MaxTriggersPerBattle > 0 ? passive.MaxTriggersPerBattle.ToString(CultureInfo.InvariantCulture) : "-") + " | " +
                                  passive.InternalCooldown + " | " +
                                  (battles == 0 ? 0.0 : (double)totals[p] / battles).ToString("0.00", CultureInfo.InvariantCulture) + " |");
            }

            report.AppendLine();
        }

        private static string Per(long total, long battles)
        {
            return (battles == 0 ? 0.0 : (double)total / battles).ToString("0.00", CultureInfo.InvariantCulture);
        }

        private static string ActiveNames(AvatarPresets avatar)
        {
            List<string> names = new List<string>();
            foreach (SkillSO skill in avatar.Actives)
            {
                names.Add(skill.DisplayName);
            }

            return names.Count == 0 ? "none" : string.Join(", ", names);
        }

        private static void AppendStats(StringBuilder report, SimOptions options, IReadOnlyList<CreatureSpeciesSO> species)
        {
            report.AppendLine("## Assembled stats at level " + options.MatrixLevel);
            report.AppendLine();
            report.AppendLine("From `StatCalculator.ComputeStats` with no gear — what each beast actually fought with at that level. **Turn rate**");
            report.AppendLine("= `TurnManager.FillRateForSpeed(Spe)` / the Speed-" + TurnManager.ReferenceSpeed + " rate: its turns per unit of normalized time (about sqrt(Spe / " +
                              TurnManager.ReferenceSpeed + ")).");
            report.AppendLine();
            report.AppendLine("| Beast | Element | Stance | HP | Atk | Def | SpA | SpD | Spe | Turn rate | Move | Crit |");
            report.AppendLine("| --- | --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |");

            foreach (CreatureSpeciesSO beast in species)
            {
                StatBlock stats = StatCalculator.ComputeStats(beast, options.MatrixLevel, null);
                report.AppendLine("| " + beast.DisplayName + " | " + PvpReport.ElementsOf(beast) + " | " + beast.Stance + " | " + stats.Hp + " | " + stats.Attack + " | " + stats.Defense +
                                  " | " + stats.SpecialAttack + " | " + stats.SpecialDefense + " | " + stats.Speed + " | " +
                                  ((double)TurnManager.FillRateForSpeed(stats.Speed) / TurnManager.ReferenceFillRate).ToString("0.000", CultureInfo.InvariantCulture) +
                                  " | " + stats.MoveRange + " | " +
                                  stats.CritChance + "% |");
            }
        }

        private static string Number(float value)
        {
            return value.ToString(CultureInfo.InvariantCulture);
        }
    }
}
